version: "3.8"

services:
    web:
        build: ./
        command: gunicorn bookCafe.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/home/app/web/staticfiles
            - ./db.sqlite3:/home/app/web/db.sqlite3
        expose:
            - 8000
        env_file:
            - ./.env
    nginx:
        build: ./nginx
        ports:
            - 1337:80
        volumes:
            - static_volume:/home/app/web/staticfiles
        depends_on:
            - web

volumes:
    static_volume:
