version: "3.8"

services:
    web:
        build: ./
        command: gunicorn bookCafe.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/home/app/web/staticfiles
            - ./db.sqlite3:/home/app/web/db.sqlite3
        expose:
            - 8000
        env_file:
            - ./.env
        networks:
            - default
    nginx:
        build: ./nginx
        volumes:
            - static_volume:/home/app/web/staticfiles
        depends_on:
            - web
        hostname: cafe-book-nginx
        networks:
            - default
            - nginx

volumes:
    static_volume:

networks:
    nginx:
        external: true
